#!/bin/bash
source /etc/profile >/dev/null

authFile=/data/account/dav_svn.authz
passwdFile=/data/account/dav_svn.passwd

usage(){
    echo -e "\033[32madd email\ndel email\033[0m"
    exit
}

mail(){
    echo -e "\n\
    Your SVN account passwd has been changed .\n\n\n\
    change time : \n\
     $(date "+[%Y-%m-%d] %H:%M:%S") \n\n\
    Your account: \n\
     ${user} \n\n\
    Your passwd: \n\
     ${passwd} \n\n\
 
    sendmail by auto deploy tools , plz don't reply ." | mailx -s "Your SVN account passwd has been changed ." ${user}
}

add(){
    user=${1}
    passwd=`tr -dc A-Za-z0-9 < /dev/urandom|head -c 10|xargs`
    htpasswd -b ${passwdFile} ${user} ${passwd}
    mail
}
del(){
    grep ${1} ${authFile} ${passwdFile} > /dev/null
    if [ $? == 0 ];then
        sed -i "/${1}/d" $passwdFile
	sed -i "s/${1}, //g" $authFile
	echo -e "\033[32m${1} has been deleted!\033[0m"
    else
        echo -e "\033[33m${1} not in ${passwdFile}\033[0m"
        exit
    fi
}
#Reload(){
#    apachectl graceful
#}
case ${1} in
    add) add ${2} ;;
    del) del ${2} ;;
    *) usage;;
esac
