#!/bin/bash
source /etc/profile
set -e
remote=172.16.8.7
tomhome=/home/webuser

#read -p "please input remoteserver:" remote

usage(){
    echo """
    ${0} ${auth/frontend/officesupport/resource/service/support}
	  include :(auth/frontend/officeSupport/resource/service/support)
    input like:
      ${0} auth #<= this will rsync auth =>#
      ${0} resource #<= this will rsync resourceManger =># 
      ${0} service  #<= this will rsync service_platform =>#
        """
}

stoptem(){
    PID=$(jps -v|grep -v grep|grep ${temname}|awk '{print $1}')
    (test ! -z "${PID}" &&
    echo -e "\033[35m stop ${temname} pid: ${PID} \033[0m" &&
    kill -9 ${PID}
    )|| echo -e "\033[33m ${temname} not running \033[0m"
}

starttem(){
    bash $tomhome/$temname/bin/startup.sh 2>&1 >/dev/null
    PID2=$(jps -v|grep -v grep|grep ${tomhome}/${temname}|awk '{print $1}')
    echo -e "\033[32m start ${temname}  pid: ${PID2} \033[0m"
}

rsync(){
    /sbin/runuser -l root -c "/usr/bin/rsync -apv --delete --exclude=spring --exclude='*.xml' --exclude='*.properties' $remote:$tomhome/$SRC/$webappdir/ $tomhome/$temname/$webappdir/"
    stoptem
  	starttem
}


case ${1} in
	  auth) SRC=auth && temname=tem-auth-1 && webappdir=webapps/tem-auth-rest && rsync ;;
	  frontend) SRC=frontend && temname=tem-frontend-1 && webappdir=webapps/tem-rest-frontend && rsync ;;
	  setting) SRC=tem-setting-1 && temname=tem-setting-1 && webappdir=webapps/tem-rest-officeSupport && rsync ;;
    resource) SRC=resourceManger && temname=tem-resource-1 && webappdir=webapps/tem-rest-resourceManager && rsync ;;
	  support)SRC==support.iclassedu.com-1&& temname=support.iclassedu.com-1 && webappdir=webapps/Service_platform && rsync ;;
  	order) SRC=support && temname=tem-order-1 && webappdir=webapps/tem-rest-support && rsync ;;
	  witkey) SRC=tem-witkey-1 && temname=tem-witkey-1 && webappdir=webapps/tem-rest-crowdsourcing &&  rsync;;
	  track ) SRC=flow_tracking && temname=track.iclassedu.com && webappdir=webapps/flow_tracking && rsync;;	
    * )  usage 2>&1;;
esac
